# Generated by Django 3.1.6 on 2021-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id_music', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=255)),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
